server:
#  port: 8003
  port: 0   # 0번 포트는 없으므로, 사실상 랜덤포트를 배정하라는 의미

spring:
  application:
    name: discovery-client

eureka:
  instance:
    #각 인스턴스별로 유레카에 보여지는 표기
    instance-id: ${spring.client.cloud.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # 유레카 서버에 등록
    fetch-registry: true # 유레카 서버에서 서버 상태 지속적 잠시
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # 유레카 서버의 주소
#      defaultZone: http://localhost:8761/eureka # ip localhost 안됨...
