server:
  port: 8003

spring:
  application:
    name: discovery-client
    
eureka:
  client:
    register-with-eureka: true # ??? ??? ????
    fetch-registry: true # ??? ???? ?? ?? ??? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # ??? ??? ??
