server:
  port: 8000

spring:
  application:
    name: apigateway-server


# 자바 config로 설정하기 위해 주석 처리
  cloud:
    gateway:
      # 전역 필터 적용 (글로벌 필터)
      default-filters:
        - name: GlobalFilter
          args:
            message: 메세지다 이놈아
            pre: true
            post: true
            # pre, post 는 boolean 타입으로 true or false
            # 필터2 추가 할 때
#        - name: GlobalFilter2
#          args:
#          message: 메세지다 이놈아
#          pre: true
#          post: true

      routes: # 개별 마이크로서비스 정보를 ROUTES에 기입
      - id : first-service
#        uri: http://localhost:8001/
        uri: lb://FIRST-SERVICE
        predicates:
          - Path=/first-service/**
        filters: # yml 파일에 필터 적용법
#          - AddRequestHeader=f-req, f-req-v
#          - AddResponseHeader=f-res, f-res-v
          # 필터명, 파라미터명이 해당 포트의 서비스(프로젝트)와 필터명, 파라미터명이 같아야 한다.
          - CustomFilter
          # 로깅 필터 적용
          - LogFilter

          # 필터 인자 설정 법 (글로벌 필터와 동일)
#          - name: CustomFilter
#             message : CustomFilter !!
#             pre : true
#             post : true

      - id : second-service
        uri: lb://SECOND-SERVICE
        predicates:
          - Path=/second-service/**
        filters:
          - CustomFilter2

      # 유저 서비스
      - id : user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user-service/**

        # 아이템 서비스
      - id: item-service
        uri: lb://ITEM-SERVICE
        predicates:
          - Path=/item-service/**

        # 오더 서비스
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order-service/**

# 유레카 연동
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true