server:
  port: 8000

spring:
  application:
    name: apigateway-server
    
#    자바 config로 설정하기 위해 주석 처리
#  cloud:
#    gateway:
#      routes: # 개별 마이크로서비스 정보를 ROUTES에 기입
#      - id : first-service
#        uri: http://localhost:8001/
#        predicates:
#          - Path=/first-service/**
#
#      - id : second-service
#        uri: http://localhost:8002/
#        predicates:
#          - Path=/second-service/**