server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:\config-github-repository
          username:
          password:
#          uri: file://C:\msa-backend\config-resource