server:
  port: 0

spring:
  application:
    name: item-service
  profiles:
    #application-db.yml
    active: db

  # MySQL
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # RabbitMQ
  rabbitmq:
    host: localhost #실제로 반영할 때는 인스턴스 내부 ip
    username: guest
    password: guest
    port: 5672

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092

# Eureka
eureka:
  instance:
    #    instance-id: ${spring.client.cloud.hostname}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # discovery-server
